//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaim.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createClaim", ReplyAction="http://tempuri.org/IService1/createClaimResponse")]
        int createClaim(System.Collections.Generic.List<DO.MitchellClaimType> createClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createClaim", ReplyAction="http://tempuri.org/IService1/createClaimResponse")]
        System.Threading.Tasks.Task<int> createClaimAsync(System.Collections.Generic.List<DO.MitchellClaimType> createClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/readClaim", ReplyAction="http://tempuri.org/IService1/readClaimResponse")]
        System.Collections.Generic.List<DO.MitchellClaimType> readClaim(DO.MitchellClaimType readClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/readClaim", ReplyAction="http://tempuri.org/IService1/readClaimResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DO.MitchellClaimType>> readClaimAsync(DO.MitchellClaimType readClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findClaimByDateRangeOfLossDate", ReplyAction="http://tempuri.org/IService1/findClaimByDateRangeOfLossDateResponse")]
        System.Collections.Generic.List<DO.MitchellClaimType> findClaimByDateRangeOfLossDate(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findClaimByDateRangeOfLossDate", ReplyAction="http://tempuri.org/IService1/findClaimByDateRangeOfLossDateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DO.MitchellClaimType>> findClaimByDateRangeOfLossDateAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/readSpecificVehicle", ReplyAction="http://tempuri.org/IService1/readSpecificVehicleResponse")]
        System.Collections.Generic.List<DO.VehicleInfoType> readSpecificVehicle(DO.MitchellClaimType readSpecificVehicleobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/readSpecificVehicle", ReplyAction="http://tempuri.org/IService1/readSpecificVehicleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DO.VehicleInfoType>> readSpecificVehicleAsync(DO.MitchellClaimType readSpecificVehicleobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteClaim", ReplyAction="http://tempuri.org/IService1/deleteClaimResponse")]
        int deleteClaim(DO.MitchellClaimType deleteClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteClaim", ReplyAction="http://tempuri.org/IService1/deleteClaimResponse")]
        System.Threading.Tasks.Task<int> deleteClaimAsync(DO.MitchellClaimType deleteClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateClaim", ReplyAction="http://tempuri.org/IService1/updateClaimResponse")]
        int updateClaim(System.Collections.Generic.List<DO.MitchellClaimType> updateClaimobjDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateClaim", ReplyAction="http://tempuri.org/IService1/updateClaimResponse")]
        System.Threading.Tasks.Task<int> updateClaimAsync(System.Collections.Generic.List<DO.MitchellClaimType> updateClaimobjDO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MitchellClaim.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MitchellClaim.ServiceReference1.IService1>, MitchellClaim.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int createClaim(System.Collections.Generic.List<DO.MitchellClaimType> createClaimobjDO) {
            return base.Channel.createClaim(createClaimobjDO);
        }
        
        public System.Threading.Tasks.Task<int> createClaimAsync(System.Collections.Generic.List<DO.MitchellClaimType> createClaimobjDO) {
            return base.Channel.createClaimAsync(createClaimobjDO);
        }
        
        public System.Collections.Generic.List<DO.MitchellClaimType> readClaim(DO.MitchellClaimType readClaimobjDO) {
            return base.Channel.readClaim(readClaimobjDO);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DO.MitchellClaimType>> readClaimAsync(DO.MitchellClaimType readClaimobjDO) {
            return base.Channel.readClaimAsync(readClaimobjDO);
        }
        
        public System.Collections.Generic.List<DO.MitchellClaimType> findClaimByDateRangeOfLossDate(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.findClaimByDateRangeOfLossDate(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DO.MitchellClaimType>> findClaimByDateRangeOfLossDateAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.findClaimByDateRangeOfLossDateAsync(startDate, endDate);
        }
        
        public System.Collections.Generic.List<DO.VehicleInfoType> readSpecificVehicle(DO.MitchellClaimType readSpecificVehicleobjDO) {
            return base.Channel.readSpecificVehicle(readSpecificVehicleobjDO);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DO.VehicleInfoType>> readSpecificVehicleAsync(DO.MitchellClaimType readSpecificVehicleobjDO) {
            return base.Channel.readSpecificVehicleAsync(readSpecificVehicleobjDO);
        }
        
        public int deleteClaim(DO.MitchellClaimType deleteClaimobjDO) {
            return base.Channel.deleteClaim(deleteClaimobjDO);
        }
        
        public System.Threading.Tasks.Task<int> deleteClaimAsync(DO.MitchellClaimType deleteClaimobjDO) {
            return base.Channel.deleteClaimAsync(deleteClaimobjDO);
        }
        
        public int updateClaim(System.Collections.Generic.List<DO.MitchellClaimType> updateClaimobjDO) {
            return base.Channel.updateClaim(updateClaimobjDO);
        }
        
        public System.Threading.Tasks.Task<int> updateClaimAsync(System.Collections.Generic.List<DO.MitchellClaimType> updateClaimobjDO) {
            return base.Channel.updateClaimAsync(updateClaimobjDO);
        }
    }
}
